apps/producto/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.lista_productos, name='lista_productos'),
    path('nuevo_producto/', views.nuevo_producto, name='nuevo_producto'),
    path('nueva_categoria/', views.nueva_categoria, name='nueva_categoria'),
    path('lista_productos/', views.lista_productos, name='lista_productos'),
    path('ver_producto/<int:pk>/', views.ver_producto, name='ver_producto'),
    path('editar_producto/<int:pk>/', views.editar_producto, name='editar_producto'),
    path('lista_categorias/', views.lista_categorias, name='lista_categorias'),
    path('editar_categoria/<int:pk>/', views.editar_categoria, name='editar_categoria'),
    path('borrar_categoria/<int:pk>/', views.borrar_categoria, name='borrar_categoria'),
    
    
    path('producto/<int:pk>/', views.detalle_producto, name='detalle_producto'),
    path('producto/<int:pk>/editar/', views.editar_producto, name='editar_producto'),
    path('producto/<int:pk>/eliminar/', views.eliminar_producto, name='eliminar_producto'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(("home.urls", "home"))),
    path("", include(("producto.urls", "producto"))),
]

apps/producto/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('detalle_categoria', args=[str(self.id)])

class Producto(models.Model):
    nombre_producto = models.CharField(max_length=200)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    imagen = models.ImageField(upload_to='productos/')
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.nombre_producto

    def get_absolute_url(self):
        return reverse('detalle_producto', args=[str(self.id)])

class Comentario(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name='comentarios')
    nombre = models.CharField(max_length=100)
    comentario = models.TextField(max_length=1000)
    created_on = models.DateTimeField(auto_now=True)
    activo = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f'Comentario de {self.nombre} en {self.producto}'

apps/producto/forms.py
from django import forms
from .models import Producto, Comentario, Categoria

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ('nombre_producto', 'descripcion', 'precio', 'imagen', 'categoria')

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ('nombre', 'comentario')

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ('nombre',)

apps/producto/views.py
# Create your views here.

from django.shortcuts import render, get_object_or_404, redirect
from .models import Producto, Categoria
from .forms import ProductoForm, CategoriaForm, ComentarioForm
from django.urls import reverse


def lista_productos(request):
    # Obtener todos los productos
    productos = Producto.objects.all()

    # Obtener todas las categorías
    categorias = Categoria.objects.all()

    # Obtener los parámetros de filtrado
    categoria_id = request.GET.get('categoria')

    # Aplicar los filtros si se han proporcionado
    if categoria_id:
        productos = productos.filter(categoria_id=categoria_id)

    # Obtener el total de productos cargados
    total_productos = productos.count()
    

    return render(request, 'producto/lista_productos.html', {'productos': productos, 'categorias': categorias, 'total_productos': total_productos})

def lista_categorias(request):
    categorias = Categoria.objects.all()
    return render(request, 'producto/lista_categorias.html', {'categorias': categorias})

def nuevo_producto(request):
    if request.method == 'POST':
        producto_form = ProductoForm(request.POST, request.FILES)
        if producto_form.is_valid():
            producto = producto_form.save(commit=False)
            producto.usuario = request.user
            producto.save()
            return redirect('/', pk=producto.pk)
    else:
        producto_form = ProductoForm()

    return render(request, 'producto/nuevo_producto.html', {'producto_form': producto_form})

def nueva_categoria(request):
    if request.method == 'POST':
        categoria_form = CategoriaForm(request.POST)
        if categoria_form.is_valid():
            nombre_categoria = categoria_form.cleaned_data['nombre']
            if Categoria.objects.filter(nombre=nombre_categoria).exists():
                # Categoría con el mismo nombre ya existe, mostrar mensaje de error o realizar alguna acción
                # Por ejemplo, puedes agregar un mensaje de error al formulario y mostrarlo en la plantilla
                categoria_form.add_error('nombre', 'La categoría ya existe.')
            else:
                categoria = categoria_form.save()
                return redirect('/nuevo_producto', id=categoria.id)
    else:
        categoria_form = CategoriaForm()

    return render(request, 'producto/nueva_categoria.html', {'categoria_form': categoria_form})


def detalle_producto(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    comentarios = producto.comentarios.filter(activo=True)

    if request.method == 'POST':
        comentario_form = ComentarioForm(request.POST)
        if comentario_form.is_valid():
            comentario = comentario_form.save(commit=False)
            comentario.producto = producto
            comentario.save()
            return redirect('/detalle_producto', pk=pk)  # Utilizar el nombre de la vista
    else:
        comentario_form = ComentarioForm()

    return render(request, 'producto/detalle_producto.html', {'producto': producto, 'comentarios': comentarios, 'comentario_form': comentario_form})


def editar_producto(request, pk):
    producto = get_object_or_404(Producto, pk=pk)

    if request.method == 'POST':
        producto_form = ProductoForm(request.POST, request.FILES, instance=producto)
        if producto_form.is_valid():
            producto = producto_form.save(commit=False)
            producto.usuario = request.user
            producto.save()
            return redirect('/lista_productos')
    else:
        producto_form = ProductoForm(instance=producto)

    return render(request, 'producto/editar_producto.html', {'producto': producto, 'producto_form': producto_form})

def eliminar_producto(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    if request.method == 'POST':
        producto.delete()
        return redirect('/lista_productos')
    
    return render(request, 'producto/eliminar_producto.html', {'producto': producto})

def ver_producto(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    return render(request, 'producto/ver_producto.html', {'producto': producto})

def editar_categoria(request, pk):
    categoria = get_object_or_404(Categoria, pk=pk)

    if request.method == 'POST':
        categoria_form = CategoriaForm(request.POST, instance=categoria)
        if categoria_form.is_valid():
            categoria_form.save()
            return redirect('/lista_categorias')
    else:
        categoria_form = CategoriaForm(instance=categoria)

    return render(request, 'producto/editar_categoria.html', {'categoria': categoria, 'categoria_form': categoria_form})

def borrar_categoria(request, pk):
    categoria = get_object_or_404(Categoria, pk=pk)

    if request.method == 'POST':
        categoria.delete()
        return redirect('/lista_categorias')

    return render(request, 'producto/borrar_categoria.html', {'categoria': categoria})

apps/producto/templates/producto/borrar_categoria.html
{% extends 'home/base.html' %}

{% block content %}
  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Borrar Categoría</h2>
      <p class="card-text">¿Estás seguro de que deseas borrar la categoría "{{ categoria.nombre }}"?</p>
      <div class="text-center">
        <form method="post" class="d-inline">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Confirmar Borrado</button>
        </form>
        <a href="/lista_categorias" class="btn btn-secondary">Cancelar</a>
      </div>
    </div>
  </div>
{% endblock %}

apps/producto/templates/producto/editar_categoria.html
{% extends 'home/base.html' %}

{% block content %}
  <h2>Editar Categoría</h2>

  <form method="post">
    {% csrf_token %}
    {{ categoria_form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
  </form>

{% endblock %}

apps/producto/templates/producto/editar_producto.html
{% extends 'home/base.html' %}

{% block content %}
  <div class="row">
    <div class="col-md-6 text-center">
      <img src="{{ producto.imagen.url }}" alt="Imagen" class="img-fluid">
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">Editar Producto</h2>
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ producto_form.as_p }}
            <button type="submit" class="btn btn-primary">Guardar cambios</button>
            <a href="/lista_productos" class="btn btn-secondary">Cancelar</a>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/producto/templates/producto/lista_categorias.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <h2>Listado de Categorías</h2>

    <!-- Imagen de presentación y detalles de categoría -->
    <div class="row mt-4">
      <div class="col-md-5">
        <img src="{% static 'home/assets/img/productos.jpg' %}" class="img-fluid rounded" alt="Imagen de presentación">
      </div>
      <div class="col-md-7">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Nombre Categoría</th>
              <th>Cantidad de Productos</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            {% for categoria in categorias %}
              <tr>
                <td>{{ categoria.nombre }}</td>
                <td>{{ categoria.producto_set.count }}</td>
                <td>
                  <a href="/editar_categoria/{{ categoria.id }}" class="btn btn-primary btn-sm">Editar</a>
                  <a href="/borrar_categoria/{{ categoria.id }}" class="btn btn-danger btn-sm">Borrar</a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

    <a href="/nueva_categoria" class="btn btn-success mt-4">Crear Categoría</a>
  </div>
{% endblock %}

apps/producto/templates/producto/lista_productos.html
{% extends 'home/base.html' %}

{% block content %}
  <h2>Lista de Productos</h2>

  <!-- Formulario de filtrado -->
  <form method="get" action="">
    <div class="row mb-3">
      <div class="col-md-4">
        <label for="categoria">Categoría:</label>
        <select name="categoria" id="categoria" class="form-control">
          <option value="">Todos</option>
          {% for categoria in categorias %}
            <option value="{{ categoria.id }}">{{ categoria.nombre }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="col-md-4 mt-4">
        <button type="submit" class="btn btn-primary">Filtrar</button>
      </div>
    </div>
  </form>

  <div class="row">
    {% for producto in productos %}
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-img-top" style="overflow: hidden; height: 200px;">
            <img src="{{ producto.imagen.url }}" class="img-fluid" style="height: 100%;" alt="Imagen">
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ producto.nombre_producto }}</h5>
            <p class="card-text">Precio: {{ producto.precio }}</p>
            <p class="card-text">Categoría: {{ producto.categoria }}</p>
            <p class="card-text">Usuario: {{ producto.usuario }}</p>
            
            <a type="button" class="btn btn-success btn-sm" href="/ver_producto/{{ producto.id }}">Ver</a>
            
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

apps/producto/templates/producto/nueva_categoria.html
{% extends 'home/base.html' %}

{% load static %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">
            <div class="text-center">
              <h2 class="card-title">Nueva Categoría</h2>
              <img src="{% static 'home/assets/img/beauty4.png' %}" alt="Imagen" class="mx-auto d-block producto-image" style="max-width: 500px;">
            </div>
          </div>
          
            <div class="card-body">
              <form method="post">
                {% csrf_token %}
                {% if categoria_form.errors %}
                  <div class="alert alert-danger">
                    <ul>
                      {% for field_errors in categoria_form.errors.values %}
                        {% for error in field_errors %}
                          <li>{{ error }}</li>
                        {% endfor %}
                      {% endfor %}
                    </ul>
                  </div>
                {% endif %}
                {{ categoria_form.as_p }}
                <button type="submit" class="btn btn-primary">Guardar</button>
              </form>
            </div>


        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/producto/templates/producto/nuevo_producto.html
{% extends 'home/base.html' %}

{% load static %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">
            <div class="text-center">
              <h2 class="card-title">Nuevo Producto</h2>
              <img src="{% static 'home/assets/img/beauty2.png' %}" alt="Imagen" class="mx-auto d-block producto-image" style="max-width: 500px;">
            </div>
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ producto_form.as_p }}
              <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/producto/templates/producto/ver_producto.html
{% extends 'home/base.html' %}

{% block content %}
  <div class="row">
    <div class="col-md-6 text-center">
      <img src="{{ producto.imagen.url }}" alt="Imagen" class="img-fluid">
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">{{ producto.nombre_producto }}</h2>
          <p class="card-text">Descripción: {{ producto.descripcion }}</p>
          <p class="card-text">Precio: {{ producto.precio }}</p>
          <p class="card-text">Categoría: {{ producto.categoria }}</p>
          <p class="card-text">Usuario: {{ producto.usuario }}</p>
          <p class="card-text">Creado por: {{ producto.usuario.username }}</p>
          <p class="card-text">Fecha de creación: {{ producto.created_on }}</p>
          <p class="card-text">Fecha de modificación: {{ producto.updated_on }}</p>
          
          {% if user.is_authenticated %}
            <a type="button" class="btn btn-success btn-sm" href="/editar_producto/{{ producto.id }}">Editar</a>
          {% else %}
            <p>Por favor, <a href="/usuarios">regístrate</a> para editar este producto.</p>
          {% endif %}
          <a href="/lista_productos" class="btn btn-success btn-sm">Volver</a>
          
        </div>
      </div>
    </div>
  </div>
{% endblock %}